version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongo:/data/db
    network_mode: 'bridge'

  sqs:
    image: roribio16/alpine-sqs:latest
    container_name: sqs
    restart: 'no'
    ports:
      - '9324:9324'
      - '9325:9325'
    network_mode: 'bridge'
