# Custom domains (API Gateway)
apiGateway:
  local:
    domainName: localhost
    certificateName: nestjs.api
    endpointType: REGIONAL

## LOCAL_ENVS
local:
  # Deploy vars
  deploy:
    deploymentBucket: 'nestjs.api'
    deploymentPrefix: nestjs.api/${self:custom.stage}
    docsBucket: 'nestjs.api'
    region: ${env:AWS_REGION}
    pruneVersion: 1
    accountId: ${env:AWS_ACCOUNT_ID}
    jwtSecret: ${env:JWT_SECRET}
    deletionPolicy: 'Delete'

  # Disable/Enable lambdas to run in background
  jobsEnabled: true

  # Base SQS Queue URL
  sqsQueue: http://${env:SQS_HOST, "127.0.0.1"}:${env:SQS_PORT, 9324}/queue/

  ssm:
    mongodb:
      host: ${env:MONGO_HOST, "mongodb.local"}
      port: ${env:MONGO_PORT, "27017"}

    # SQS Credentials
    sqs:
      host: ${env:SQS_HOST, "127.0.0.1"}
      port: ${env:SQS_PORT, "9324"}
